name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AadityaBhuree
          outputs: |
            dist/github-snake.svg?color_snake=%232f80ed&color_dots=%23ebedf0,%23cce4ff,%2399c9ff,%234da3ff,%232f80ed

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
